# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: GoLang CI Build-Test
run-name: ${{ github.actor }} is push code to main 🚀
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: go build -v ./cmd/...

      - name: Test
        run: go test -v ./... -tags ci
